// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0LB3OYy-9NJ-J1emu8i9o4bYIGO8BX3c',
    appId: '1:582062635622:web:8d487bf8bad74df4544ba7',
    messagingSenderId: '582062635622',
    projectId: 'weather-app-4e640',
    authDomain: 'weather-app-4e640.firebaseapp.com',
    storageBucket: 'weather-app-4e640.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbujuetXS9apIxFEmb116-8k-W-WJW1XQ',
    appId: '1:582062635622:android:721b721156efaaba544ba7',
    messagingSenderId: '582062635622',
    projectId: 'weather-app-4e640',
    storageBucket: 'weather-app-4e640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoka32IqsnbKD9MFPtx0lGFKReJG_S960',
    appId: '1:582062635622:ios:05b5267638668028544ba7',
    messagingSenderId: '582062635622',
    projectId: 'weather-app-4e640',
    storageBucket: 'weather-app-4e640.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoka32IqsnbKD9MFPtx0lGFKReJG_S960',
    appId: '1:582062635622:ios:05b5267638668028544ba7',
    messagingSenderId: '582062635622',
    projectId: 'weather-app-4e640',
    storageBucket: 'weather-app-4e640.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0LB3OYy-9NJ-J1emu8i9o4bYIGO8BX3c',
    appId: '1:582062635622:web:ec78df8e833057f2544ba7',
    messagingSenderId: '582062635622',
    projectId: 'weather-app-4e640',
    authDomain: 'weather-app-4e640.firebaseapp.com',
    storageBucket: 'weather-app-4e640.firebasestorage.app',
  );

}